"""empty message

Revision ID: 324d992e0057
Revises: d5c4a01a375e
Create Date: 2025-02-08 00:34:42.342552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324d992e0057'
down_revision = 'd5c4a01a375e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=9999), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
