"""empty message

Revision ID: 61a28598abd5
Revises: e1f7f6eef86a
Create Date: 2025-02-08 00:45:39.958669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a28598abd5'
down_revision = 'e1f7f6eef86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chaperone_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chaperone_slot', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
