"""empty message

Revision ID: 96478b93b1be
Revises: c9188cd47a7d
Create Date: 2025-02-09 21:24:36.686759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96478b93b1be'
down_revision = 'c9188cd47a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chaperone_slot', schema=None) as batch_op:
        batch_op.drop_constraint('chaperone_slot_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chaperone_slot', schema=None) as batch_op:
        batch_op.create_foreign_key('chaperone_slot_ibfk_1', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
