"""empty message

Revision ID: c9188cd47a7d
Revises: a9893fceb316
Create Date: 2025-02-09 20:18:55.862175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9188cd47a7d'
down_revision = 'a9893fceb316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_chaperone', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('lead_chaperone')

    # ### end Alembic commands ###
