"""empty message

Revision ID: e1f7f6eef86a
Revises: 324d992e0057
Create Date: 2025-02-08 00:45:09.601159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f7f6eef86a'
down_revision = '324d992e0057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chaperone_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=9999), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chaperone_slot', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
