/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./components/ActionsMenu.vue')['default']
    AlertDialog: typeof import('./components/AlertDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AvailabilitySelector: typeof import('./components/AvailabilitySelector.vue')['default']
    ChaperonesPage: typeof import('./components/chaperonesPage.vue')['default']
    CreateTermDialog: typeof import('./components/CreateTermDialog.vue')['default']
    EditPage: typeof import('./components/EditPage.vue')['default']
    EventCard: typeof import('./components/EventCard.vue')['default']
    PWAInstallDialog: typeof import('./components/PWAInstallDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchedulePage: typeof import('./components/SchedulePage.vue')['default']
    TimePicker: typeof import('./components/TimePicker.vue')['default']
  }
}
