/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...page]': RouteRecordInfo<'/[...page]', '/:page(.*)', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/availability': RouteRecordInfo<'/availability', '/availability', Record<never, never>, Record<never, never>>,
    '/chaperones': RouteRecordInfo<'/chaperones', '/chaperones', Record<never, never>, Record<never, never>>,
    '/editEvent': RouteRecordInfo<'/editEvent', '/editEvent', Record<never, never>, Record<never, never>>,
    '/event': RouteRecordInfo<'/event', '/event', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/offline': RouteRecordInfo<'/offline', '/offline', Record<never, never>, Record<never, never>>,
    '/passwordLogin': RouteRecordInfo<'/passwordLogin', '/passwordLogin', Record<never, never>, Record<never, never>>,
    '/schedule': RouteRecordInfo<'/schedule', '/schedule', Record<never, never>, Record<never, never>>,
    '/templateEvents': RouteRecordInfo<'/templateEvents', '/templateEvents', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
